# Generated by Django 3.1.7 on 2021-03-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataSchemas',
        ),
    ]
