# Generated by Django 3.1.7 on 2021-03-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210323_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSchemas',
            new_name='Data',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-id'], 'verbose_name': 'Data Set', 'verbose_name_plural': 'Data Sets'},
        ),
    ]
