# Generated by Django 3.1.7 on 2021-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20210323_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
