# Generated by Django 3.1.7 on 2021-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20210323_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='separator',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='string_char',
        ),
    ]
