# Generated by Django 3.1.7 on 2021-03-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20210323_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='slug',
        ),
    ]
