# Generated by Django 3.1.7 on 2021-03-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_remove_schema_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
