# Generated by Django 3.1.7 on 2021-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_column_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
