# Generated by Django 3.1.7 on 2021-03-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_auto_20210323_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='schemas.column'),
        ),
    ]
