# Generated by Django 3.1.7 on 2021-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0014_auto_20210323_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='schema',
        ),
        migrations.AddField(
            model_name='data',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
