# Generated by Django 3.1.7 on 2021-03-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0015_auto_20210323_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='schema',
            new_name='name',
        ),
    ]
