# Generated by Django 3.1.7 on 2021-03-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0016_auto_20210323_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='schema',
        ),
    ]
